'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';
import { MyButton as MyButtonElement, defineCustomElement as defineMyButton } from "../../../../stencil/dist/components/my-button.js";
import { MyComponent as MyComponentElement, defineCustomElement as defineMyComponent } from "../../../../stencil/dist/components/my-component.js";
import { MyList as MyListElement, defineCustomElement as defineMyList } from "../../../../stencil/dist/components/my-list.js";
import { MyTitle as MyTitleElement, defineCustomElement as defineMyTitle } from "../../../../stencil/dist/components/my-title.js";

type MyButtonEvents = NonNullable<unknown>;

export const MyButton: StencilReactComponent<MyButtonElement, MyButtonEvents> = /*@__PURE__*/ createComponent<MyButtonElement, MyButtonEvents>({
    tagName: 'my-button',
    elementClass: MyButtonElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as MyButtonEvents,
    defineCustomElement: defineMyButton
});

type MyComponentEvents = NonNullable<unknown>;

export const MyComponent: StencilReactComponent<MyComponentElement, MyComponentEvents> = /*@__PURE__*/ createComponent<MyComponentElement, MyComponentEvents>({
    tagName: 'my-component',
    elementClass: MyComponentElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as MyComponentEvents,
    defineCustomElement: defineMyComponent
});

type MyListEvents = NonNullable<unknown>;

export const MyList: StencilReactComponent<MyListElement, MyListEvents> = /*@__PURE__*/ createComponent<MyListElement, MyListEvents>({
    tagName: 'my-list',
    elementClass: MyListElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as MyListEvents,
    defineCustomElement: defineMyList
});

type MyTitleEvents = NonNullable<unknown>;

export const MyTitle: StencilReactComponent<MyTitleElement, MyTitleEvents> = /*@__PURE__*/ createComponent<MyTitleElement, MyTitleEvents>({
    tagName: 'my-title',
    elementClass: MyTitleElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: {} as MyTitleEvents,
    defineCustomElement: defineMyTitle
});
